project:
  type: website

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: miipw.qmd
        text: miipw
      - href: Resume.qmd
        text: CV
      - href: portfolio.qmd
        text: portfolio
      - href: projects.qmd
        text: projects
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

