
---
title: "R Packages"
format: html
---

# 📦 My R Packages

Below are the R packages I have developed or contributed to. These packages address various statistical modeling and data analysis challenges, particularly for longitudinal and survival data.

---

## 🔹 MIIPW

**Description:**  
An R package for fitting Generalized Estimating Equations (GEE) with missing data using a combination of Mean Score (MS), Inverse Probability Weighting (IPW), and Multiple Imputation (MI).

- 📦 [CRAN](https://cran.r-project.org/web/packages/MIIPW/index.html)
- 🔗 [GitHub](https://github.com/kumarbhrigu/MIIPW)
- 📄 [Documentation](https://kumarbhrigu.github.io/MIIPW/)

---

## 🔹 jmBIG

**Description:**  
A flexible and scalable joint modeling toolkit for large longitudinal and survival datasets. Supports `JMbayes2`, `rstanarm`, `joineRML`, and `FastJM`.

- 📦 [CRAN](https://cran.r-project.org/web/packages/jmBIG/index.html)
- 🔗 [GitHub](https://kumarbhrigu.github.io/jmBIG/)
- 📄 [Documentation](https://kumarbhrigu.github.io/jmBIG/)
---

## 🔹 JMtwostage

**Description:**  
Implements two-stage joint modeling of longitudinal and survival outcomes for scenarios where traditional joint models may be computationally heavy. The package installed using the following code 

```r
# Install the remotes package if not already installed
install.packages("remotes")

# Install JMtwostage from GitHub
remotes::install_github("kumarbhrigu/JMtwostage")
```

- 🔗 [GitHub](https://kumarbhrigu.github.io/JMtwostage/)
- 📄 [Documentation](https://kumarbhrigu.github.io/JMtwostage/)
---

## 🔹 JMbdirect: Joint Model for Longitudinal and Multiple Time to Events Data

**Description:**  
Provides model fitting, prediction, and plotting for joint models of longitudinal and multiple time-to-event data, including methods from Rizopoulos (2012) <doi:10.1201/b12208>. Useful for handling complex survival and longitudinal data in clinical research.

- 📦 [CRAN](https://cran.r-project.org/web/packages/JMbdirect/index.html)
- 🔗 [GitHub](https://kumarbhrigu.github.io/JMbdirect/)
- 📄 [Documentation](https://kumarbhrigu.github.io/JMbdirect/)
