---
title: "R Shiny app"
format: html
---

Below are the R shiny app I have developed. These apps are related to packages developed for  various statistical modeling and data analysis challenges, particularly for longitudinal and survival data.

---

## Shiny app for r package jmBIG

**Date:** April 12, 2024  
**Summary:**  
The **jmBIG** Shiny app provides powerful analytical tools tailored for **BIG data**, where the number of observations (rows) is extremely large. It enables users to perform **joint modeling** of longitudinal

**[Read More ›](blogs/jmBIGshinny.qmd)**

---

## 🔹 lmeIPW

**Date:** April 13, 2024  
**Summary:**  
The **MIIPW** R package provides robust tools for analyzing **repeated measurement data** using a **semiparametric marginal modeling** framework.

**[Read More ›](blogs/lmeIPW.qmd)**


- 📦 [CRAN](https://cran.r-project.org/web/packages/MIIPW/index.html)
- 🔗 [GitHub](https://github.com/kumarbhrigu/MIIPW)
- 🔗 [Explore the app here](https://bhrigukr.shinyapps.io/lmemiipw/)
- 📄 [Documentation](https://kumarbhrigu.github.io/MIIPW/)

---

## 🔹 dscoreMSM

**Description:**  
This is the R Shiny app for our R package dscoreMSM. Our package includes various functions required for our proposed method named Survival Proximity Score Matching to handle doubtful censored cases in a multistate survival model. The hazard function for different transitions follows a CoxPH model with a transition-specific frailty term

- 📦 [CRAN](https://cran.r-project.org/web/packages/dscoreMSM/index.html)
- 🔗 [Explore the app here](https://atanu.shinyapps.io/dscoremsmnew-1/#section-dscore)
